### ISSUE TITLE
Creating Notebook Failed

### ISSUE THREAD

**Issue by KrashLeviathan** [googledatalab/datalab#2021]
After having setup Datalab for the first time (following the documentation), I cannot create a new notebook. The following is the dialog box that pops up after clicking the "+ Notebook" button:

![2018-06-12 12_38_52-google cloud datalab](https://user-images.githubusercontent.com/8837587/41307022-a56ba8f6-6e3d-11e8-8c42-ec9e4f3ae6d0.png)

The developer console shows the following error:

![2018-06-12 12_39_01-google cloud datalab](https://user-images.githubusercontent.com/8837587/41307033-adbe4644-6e3d-11e8-8f18-69c44a1f86c9.png)

I'm running the latest version of Google Chrome on Windows. The Datalab connection was made inside Google Cloud Shell. The process for creating the Datalab was running: `datalab create my-datalab` from the cloud shell. Before doing this, I enabled Google Compute Engine and Cloud Source Repositories APIs. I'm in the free trial period of GCP, with billing enabled and almost the full balance of free trial credits still available.

**Comment by rileyjbauer** [comment]
Thanks for the report!
We've rolled back the bad release, and creating a new Datalab instance now should resolve the issue you are seeing.

I filed #2022 to track this issue further

**Comment by daniol1618** [comment]
![image](https://user-images.githubusercontent.com/51725475/90303574-a8ee8d00-de74-11ea-915a-39043f88ac69.png)

**Comment by jigna-panchal** [comment]
I'm getting the same issue, not sure where the problem is. Can someone help?

**Comment by Arunky122** [comment]
> I'm getting the same issue, not sure where the problem is. Can someone help?

I am also getting the same issue , even I can create a new instance it still shows me this error !!!!

**Comment by hichMEN** [comment]
Mee too, I can't create, update or run my notebooks

**Comment by GabiAndradeD** [comment]
I am also getting the same issue

**Comment by sumitparkhani** [comment]
Having the same issue

**Comment by jakrapansuk** [comment]
getting the same issue same here.
our datalab connection was made inside google cloud shell as well.

**Comment by hanane-tr** [comment]
Hello,
I'm getting the same issue here, any update please ?

**Comment by erankitcs** [comment]
Hello Team,
I am also getting the same error during the creation of a notebook and folder both.
Thanks,

Ankit
